FEATURE_F0_MIDI_SCALED = 'f0_midi_scaled'
FEATURE_LD_SCALED = 'ld_scaled'
FEATURE_F0_HZ = 'f0_hz'
FEATURE_Z = 'z'

INPUT_FEATURE_LOUDNESS_DB = 'loudness_db'
INPUT_FEATURE_F0_HZ = 'f0_hz'
INPUT_FEATURE_MFCC = 'mfcc'
INPUT_FEATURE_LOG_MEL = 'log_mel'

MIDI_FEATURE_VELOCITY = 'velocity'
MIDI_FEATURE_PITCH = 'pitch'
MIDI_FEATURE_DISTANCE_FROM_ONSET = 'distance_from_onset'
MIDI_FEATURE_DISTANCE_TO_OFFSET = 'distance_to_offset'
MIDI_FEATURE_CC_PREFIX = 'cc_'


