#run_name: Latent_NoReverb
run_name: Latent_NoReverb_ConfFiltered
#run_name: Latent_NoReverb_Normalized
# Leave empty for not using wandb
wandb:
  project_name: Violin
data:
  instrument: Violin
  path: /kuacc/users/hbalim15/ddsp/audio_clips/Violin
  # Frame rate at the encoder
  preprocessing_time: 250
  sample_rate: 16000
  # confidence threshold level for f0
  # put 0.0 for not using
  confidence_threshold: 0.85
  # Apply audio normaliztion
  normalize: False
model:
  type: Supervised
  # Frame rate at the decoder
  decoder_time: 1000
  # Use the z encoder or not
  encoder: True
  # Whether to use the reverb module
  reverb: False
  # Directory to save the model in
  # leave empty for auto 
  dir:  
loss:
  type: spectral
  logmag_weight: 1.0
optimizer:
  name: Adam
  decay_rate: 0.98
  decay_steps: 10000
  lr: 0.001
training:
  batch_size: 32
  epochs: 1000