run_name: Unsupervised_Violin
# Leave empty for not using wandb
wandb:
#  project_name: Unsupervised_Violin
data:
  path: /kuacc/users/hbalim15/ddsp/audio_clips/Violin_short
  # Frame rate at the encoder
  preprocessing_time: 250
  sample_rate: 16000
  # confidence threshold level for f0
  # put 1.0 for not using
  normalize: False
  confidence_threshold: 0.0  
model:
  type: Supervised
  # Frame rate at the decoder
  decoder_time: 1000
  # Whether to use the reverb module
  reverb: true
  # Directory to save the model in
  # leave empty for auto 
  dir:  
loss:
  type: spectral
  logmag_weight: 1.0
optimizer:
  name: Adam
  decay_rate: 0.98
  decay_steps: 10000
  lr: 0.001
training:
  batch_size: 32
  epochs: 1000